changelog:
  categories:
    - title: New features
      labels:
        - 'enhancement'

    - title: Fixed bugs
      labels:
        - 'bug'

    - title: Dependency updates
      labels:
        - 'dependencies'

    - title: Chores & Other
      labels:
        - '*'