name: Release

on:
  push:
    tags:
      - v*

jobs:
  tests:
    uses: ./.github/workflows/run-tests.yml
    secrets: inherit

  release:
    needs:
      - tests
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Cache
        uses: actions/cache@v4
        with:
          key: ${{ runner.os }}-build-${{ github.head_ref || github.ref_name }}
          restore-keys: |
            ${{ runner.os }}-build-main
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            ./**/.gradle
            ./**/build

      - name: Publish on Plugin Portal
        run: ./gradlew release-plugin:publishPlugins
        env:
          GRADLE_PUBLISH_KEY: ${{ secrets.GRADLE_PUBLISH_KEY }}
          GRADLE_PUBLISH_SECRET: ${{ secrets.GRADLE_PUBLISH_SECRET }}

      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
          append_body: false
          make_latest: true